# Maintainers:
#   - name: Roman Rabodzei
#   - date: 7/4/2023
#   - filename: chart.yaml

apiVersion: v2
name: contoso-website
description: A Helm chart for Kubernetes.
type: application
version: 0.1.0
appVersion: 1.0.0

keywords:
  - aks
  - microsoft
