# Maintainers:
#   - name: Roman Rabodzei
#   - date: 8/1/2023
#   - filename: values.yaml
#   - description: default vaules for helm chart

container:
  image: mcr.microsoft.com/mslearn/samples/contoso-website

replicaCount: 2

autoscaling:
  minReplicas: 2
  maxReplicas: 8

ingress:
  enabled: true
  extraHosts:
    hostname: contoso
