# Maintainers:
#   - name: Roman Rabodzei
#   - date: 7/4/2023
#   - filename: service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: ClusterIP
  selector:
    app: contoso-website # template selector
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http