name: Build and push the latest build to staging

on:
  push:
    branches: [ main ]

jobs:
  build_push_image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag contoso-website:latest

      - name: Push the Docker Image
        run: docker push ${{secrets.ACR_NAME}}/contoso-website:latest

  deploy:
    runs-on: ubuntu-20.04
    needs: build_push_image

    steps:
      - uses: actions/checkout@v2

      - name: Install Helm
        uses: Azure/setup-helm@v1
        with:
          version: v3.12.1

      - name: Get AKS Credentials
        uses: Azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{secrets.AKS_RESOURCE_GROUP}}
          cluster-name: contoso-video

      - name: Run Helm Deploy
        run: |
          helm upgrade \
            contoso-app \
            ./helm-chart \
            --set container.image=${{secrets.ACR_NAME}}/contoso-website:latest